-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 09:48:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CM_JEUX
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CM_JEUX` ;

-- -----------------------------------------------------
-- Schema CM_JEUX
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CM_JEUX` DEFAULT CHARACTER SET utf8 ;
USE `CM_JEUX` ;

-- -----------------------------------------------------
-- Table `CM_JEUX`.`Console`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CM_JEUX`.`Console` ;

CREATE TABLE IF NOT EXISTS `CM_JEUX`.`Console` (
  `idconsole` INT NOT NULL AUTO_INCREMENT,
  `console` VARCHAR(45) NOT NULL,
  `prix` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idconsole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CM_JEUX`.`Dev`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CM_JEUX`.`Dev` ;

CREATE TABLE IF NOT EXISTS `CM_JEUX`.`Dev` (
  `idDev` INT NOT NULL AUTO_INCREMENT,
  `direction` VARCHAR(45) NOT NULL,
  `lieux` VARCHAR(45) NOT NULL,
  `chiffreAffaire` VARCHAR(45) NOT NULL,
  `console` INT NULL,
  PRIMARY KEY (`idDev`),
  INDEX `dev_idx` (`console` ASC) VISIBLE,
  CONSTRAINT `dev`
    FOREIGN KEY (`console`)
    REFERENCES `CM_JEUX`.`Console` (`idconsole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CM_JEUX`.`Joueur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CM_JEUX`.`Joueur` ;

CREATE TABLE IF NOT EXISTS `CM_JEUX`.`Joueur` (
  `idJoueur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `surnom` VARCHAR(45) NOT NULL,
  `age` DATE NOT NULL,
  `console` INT NOT NULL,
  PRIMARY KEY (`idJoueur`),
  INDEX `joueur_idx` (`console` ASC) VISIBLE,
  CONSTRAINT `joueur`
    FOREIGN KEY (`console`)
    REFERENCES `CM_JEUX`.`Console` (`idconsole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CM_JEUX`.`Auteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CM_JEUX`.`Auteur` ;

CREATE TABLE IF NOT EXISTS `CM_JEUX`.`Auteur` (
  `idauteur` INT NOT NULL AUTO_INCREMENT,
  `surnom` VARCHAR(15) NOT NULL,
  `nom` VARCHAR(15) NOT NULL,
  `reultat` VARCHAR(45) NULL,
  PRIMARY KEY (`idauteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CM_JEUX`.`Avis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CM_JEUX`.`Avis` ;

CREATE TABLE IF NOT EXISTS `CM_JEUX`.`Avis` (
  `idAvis` INT NOT NULL AUTO_INCREMENT,
  `auteur` INT NOT NULL,
  `note` VARCHAR(45) NOT NULL,
  `dersciption` VARCHAR(45) NOT NULL,
  `joueur` INT NOT NULL,
  PRIMARY KEY (`idAvis`),
  INDEX `joueur_idx` (`joueur` ASC) VISIBLE,
  INDEX `avis_idx` (`auteur` ASC) VISIBLE,
  CONSTRAINT `avis`
    FOREIGN KEY ()
    REFERENCES `CM_JEUX`.`Avis` ()
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `joueur`
    FOREIGN KEY (`joueur`)
    REFERENCES `CM_JEUX`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `avis`
    FOREIGN KEY (`auteur`)
    REFERENCES `CM_JEUX`.`Auteur` (`idauteur`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CM_JEUX`.`PEGI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CM_JEUX`.`PEGI` ;

CREATE TABLE IF NOT EXISTS `CM_JEUX`.`PEGI` (
  `idPEGI` INT NOT NULL,
  `note` VARCHAR(2) NOT NULL,
  `detail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPEGI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CM_JEUX`.`Jeux`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CM_JEUX`.`Jeux` ;

CREATE TABLE IF NOT EXISTS `CM_JEUX`.`Jeux` (
  `idJeux` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(45) NOT NULL,
  `dateSortie` DATE NOT NULL,
  `dev` VARCHAR(45) NOT NULL,
  `avis` INT NOT NULL,
  `pegi` INT NOT NULL,
  PRIMARY KEY (`idJeux`),
  INDEX `jeux_idx` (`dev` ASC) VISIBLE,
  INDEX `avis_idx` (`avis` ASC) VISIBLE,
  INDEX `jeux_idx1` (`pegi` ASC) VISIBLE,
  CONSTRAINT `jeux`
    FOREIGN KEY (`dev`)
    REFERENCES `CM_JEUX`.`Dev` (`idDev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `avis`
    FOREIGN KEY ()
    REFERENCES `CM_JEUX`.`Avis` ()
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `avis`
    FOREIGN KEY (`avis`)
    REFERENCES `CM_JEUX`.`Avis` (`idAvis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `jeux`
    FOREIGN KEY (`pegi`)
    REFERENCES `CM_JEUX`.`PEGI` (`idPEGI`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
